language: r
r: devel
cache: packages

r_check_args: "--as-cran --run-dontrun"
warnings_are_errors: false
sudo: required

notifications:
 email:
  on_success: change
  on_failure: change
    
r_github_packages: sdray/ade4

addons:
 apt:
  packages:
   - libudunits2-dev
   - libgdal-dev
