library(adegraphics)
pdf("s1d.density.pdf")

x1 <- rnorm(1000)
g11 <- s1d.density(x1)
g12 <- s1d.density(x1, fill = TRUE, ppoly.col = "blue", p1d.rev = TRUE)
g13 <- s1d.density(x1, fill = TRUE, ppoly.col = "blue", p1d.hori = FALSE)
g13 <- s1d.density(x1, fill = TRUE, ppoly.col = "blue", p1d.hori = FALSE, p1d.rev = TRUE)

x2 <- c(rnorm(1000, mean = -0.5, sd = 0.5), rnorm(1000, mean = 1))
fact <- rep(c("A", "B"), each = 1000)
g21 <- s1d.density(x2, fact, col = c("red", "blue"))
g22 <- s1d.density(x2, fact, col = FALSE, ppoly.col = 2:3)
g23 <- s1d.density(x2, fact, col = FALSE, ppoly.col = 2:3, fill = TRUE, p1d.rev = TRUE)
g24 <- s1d.density(x2, fact, col = FALSE, ppoly.col = 2:3, fill = TRUE, p1d.horizontal = FALSE)
g24 <- s1d.density(x2, fact, col = FALSE, ppoly.col = 2:3, fill = TRUE, p1d.horizontal = FALSE, p1d.rev = TRUE)
